version: '3'
services:
  frontend:
    build:
      context: ./netoflixo
    ports:
      - "5173:5173"
  backend:
    build:
      context: ./api
    ports:
      - "3000:3000"
    depends_on:
      - database
  database:
    image: "mongo:latest"
    restart: always

volumes:
  database_data: {}